pr_workflow_type: devops
repository:  
  description: |
    This repository
    Does stuff 1212

labels:
  - name: Needs Review
    color: FFF123
    description: Ready for review

regex_labels:
  - regex: \d+\.\d+\.\d+
    color: FFFFFF
    description: Version labels
